cloud:
  aws:
    s3:
      bucket: project-clone
    credentials:
      accessKey: AKIAQ4TZNFUBVY66YOGZ
      secretKey: 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
      instanceProfile: true
    region:
      static: ap-northeast-2
      # bucket update 안 될 경우;
      auto: false
    stack:
      auto: false
